package com.example.predictor_mundial.enums;

public enum SeleccionMundial {

	ARGENTINA, AUSTRALIA, AUSTRIA, BELGICA, BOSNIA_Y_HERZEGOVINA, BRASIL, CANADA, COLOMBIA, COREA_DEL_SUR,
	COSTA_DE_MARFIL, COSTA_RICA, CROACIA, CURAZAO, DINAMARCA, ECUADOR, EGIPTO, EL_SALVADOR, EMIRATOS_ARABES_UNIDOS,
	ESPANA, ESTADOS_UNIDOS, FRANCIA, GHANA, HAITI, HONDURAS, INGLATERRA, IRAN, IRAK, JAMAICA, JAPON, JORDANIA,
	MARRUECOS, MEXICO, NORUEGA, NUEVA_ZELANDA, PAISES_BAJOS, PANAMA, PARAGUAY, POLONIA, PORTUGAL, QATAR,
	REPUBLICA_CHECA, REPUBLICA_DEMOCRATICA_DEL_CONGO, SENEGAL, SUIZA, SUDAFRICA, TUNEZ, TURQUIA, URUGUAY, UZBEKISTAN,
	ALEMANIA, ITALIA, SERBIA, CAMERUN, ARABIA_SAUDITA

}